# Generated by Django 2.2.4 on 2020-09-11 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_candidate'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='vote',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
