# Generated by Django 2.2.4 on 2020-09-15 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_election'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='image',
            field=models.ImageField(default=20, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidate',
            name='percent',
            field=models.IntegerField(default=20),
            preserve_default=False,
        ),
    ]
