# Generated by Django 2.2.4 on 2020-09-15 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_auto_20200915_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='percent',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
