# Generated by Django 2.2.4 on 2020-09-15 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_auto_20200915_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='percent',
            field=models.IntegerField(default=0),
        ),
    ]
