# Generated by Django 2.2.4 on 2020-09-25 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0012_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='percent',
            field=models.FloatField(default='0'),
        ),
    ]
