# Generated by Django 2.2.4 on 2020-10-05 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0015_candidate_reg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate_reg',
            name='financial_status',
        ),
        migrations.AddField(
            model_name='candidate_reg',
            name='financial',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='candidate_reg',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='candidate_reg',
            name='attendance_status',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='candidate_reg',
            name='chapter',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='candidate_reg',
            name='chapter_year',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='candidate_reg',
            name='date_of_birth',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='candidate_reg',
            name='dishonesty_status',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='candidate_reg',
            name='education',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='candidate_reg',
            name='email',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='candidate_reg',
            name='executive_status',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='candidate_reg',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='candidate_reg',
            name='last_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='candidate_reg',
            name='occupation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='candidate_reg',
            name='other_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='candidate_reg',
            name='phone',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='candidate_reg',
            name='position',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='candidate_reg',
            name='sex',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='candidate_reg',
            name='title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
