# Generated by Django 2.2.4 on 2020-10-05 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0016_auto_20201005_1118'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate_reg',
            name='executive_officer',
            field=models.TextField(blank=True, null=True),
        ),
    ]
