# Generated by Django 2.2.4 on 2020-10-05 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0017_candidate_reg_executive_officer'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate_reg',
            name='admission_date',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidate_reg',
            name='graduation_date',
            field=models.TextField(blank=True, null=True),
        ),
    ]
