# Generated by Django 2.2.4 on 2020-10-15 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0020_auto_20201015_0128'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
