# Generated by Django 2.2.4 on 2020-10-15 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0021_userprofile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate_reg',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
