# Generated by Django 2.2.4 on 2020-10-15 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0022_candidate_reg_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate_reg',
            name='percent',
            field=models.FloatField(default='0'),
        ),
        migrations.AddField(
            model_name='candidate_reg',
            name='vote',
            field=models.IntegerField(default='0'),
        ),
    ]
