# Generated by Django 2.2.4 on 2020-10-15 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0024_auto_20201015_0906'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='name_title',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
