# Generated by Django 2.2.4 on 2020-10-27 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0028_userprofile_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='time',
            name='name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
